#!/bin/sh
#
# file : pre-commit
# desc : This hook dump your prestashop database in dump.sql and add this file (git add) before the commit.
#        The dump is made with --skip-extended-insert option to make database state comparaison really easy.
#        This hook is the reciprocal of post-checkout. 
#        
#
# author : Michaël Marineti
# creation : 2012-04-30
# modified : 2012-05-28
#
# CHANGELOG
# 2012-05-28
# clean code, add comments

db_to_save=`grep DB_NAME config/settings.inc.php  |awk -F\' '{print $4}'`
dbuser="`grep DB_USER config/settings.inc.php  |awk -F\' '{print $4}'`"
dbpass="`grep DB_PASSWD config/settings.inc.php  |awk -F\' '{print $4}'`"
if (test -z $dbpass) then
	mysql_conn_string="-u$dbuser"
else
	mysql_conn_string="-u$dbpass -p$dbpass"
fi
mysqldump $mysql_conn_string --skip-comments --skip-extended-insert $db_to_save > dump.sql
if (test $? -ne 0) then
	echo "error on mysqldump"
	exit 1
fi

git add dump.sql 

